create database emp;
use emp;

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
  ENO INT PRIMARY KEY,
  NAME VARCHAR(50),
  GENDER CHAR(1),
  DOB DATE,
  DOJ DATE,
  DESIGNATION VARCHAR(50),
  BASIC DECIMAL(10, 2),
  DEPT_NO INT,
  PAN VARCHAR(10),
  SENO INT,
  CONSTRAINT CHK_GENDER CHECK (GENDER IN ('M', 'F')),
  CONSTRAINT CHK_PAN CHECK (LENGTH(PAN) = 10),
  CONSTRAINT CHK_SENO CHECK (SENO > 0)
);

-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
  DEPT_NO INT PRIMARY KEY,
  NAME VARCHAR(50),
  MENO INT,
  FOREIGN KEY (MENO) REFERENCES EMPLOYEE(ENO)
);

-- Populate the tables with sample data
INSERT INTO DEPARTMENT (DEPT_NO, NAME, MENO) VALUES
  (101, 'HR', 101),
  (102, 'Finance', 102);

INSERT INTO EMPLOYEE (ENO, NAME, GENDER, DOB, DOJ, DESIGNATION, BASIC, DEPT_NO, PAN, SENO) VALUES
  (101, 'John', 'M', '1985-03-15', '2010-07-01', 'Manager', 60000.00, 101, 'ABCDE1234F', NULL),
  (102, 'Mary', 'F', '1990-05-20', '2015-04-15', 'Manager', 65000.00, 102, 'FGHIJ5678K', 101);
  select *from employee;
  select*from department;
  
-- Drop the foreign key constraint
ALTER TABLE DEPARTMENT drop FOREIGN KEY MENO;
DESC DEPARTMENT;

