use students;
create table std (rollnumber int,name varchar(10),address varchar(30),subject varchar(15),total_mark int);
insert into std values(1,'kuttu','kozhikode','physics',80);
insert into std values(2,'anandu','kochi','php',50);
insert into std values(3,'Hari','kannur','c++',72);
insert into std values(4,'ammu','kollam','cs',98);
insert into std values(5,'arjun','kozhikode','mathematics',350);
insert into std values(6,'arun','malappuram','chemistry',370);
select * from std;
select rollnumber,name from std;
select * from std where address='kozhikode';
select * from std where(total_mark>=350);
select * from std where address='kozhikode' or address='kochi';
alter table std add (dept varchar(10));
update std set dept='MSC' where rollnumber=1;
update std set dept='MCA' where rollnumber=2;
update std set dept='EEE' where rollnumber=3;
update std set dept='MBA' where rollnumber=4;
update std set dept='MCOM' where rollnumber=5;
update std set dept='MCA' where rollnumber=6;
update std set subject="mathematics" where rollnumber=3;
select * from std order by name,dept desc;
select max(total_mark) as highest_mark from std;
select min(total_mark) as lowest_mark from std where subject='mathematics';
select avg(total_mark) from std where subject="cs";
select sum(total_mark) as sum_of from std where subject="physics";
update std set address=null where rollnumber=3;
select max(total_mark) as highest_mark from std;
